import { ImageOff } from 'lucide-react';
import { mediaUrl } from '../services/api';
export default function GradCam({ url }) { return <div className="image-panel"><div className="image-panel-head"><span><span className="eyebrow">Model explanation</span><b>Grad-CAM visualization</b></span></div>{url ? <img src={mediaUrl(url)} alt="Grad-CAM visualization generated by the AI model" /> : <div className="image-empty"><ImageOff size={24}/><span>Grad-CAM was not returned for this screening.</span></div>}</div>; }
