# Generated by Django 6.0.3 on 2026-09-06 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('diabetes_duration', models.PositiveIntegerField(help_text='Years')),
                ('hba1c', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PHCWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phc_id', models.CharField(max_length=20, unique=True)),
                ('phc_name', models.CharField(default='Rampur', max_length=100)),
                ('unit', models.CharField(default='Rural Health Screening Unit 01', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_side', models.CharField(choices=[('OD', 'Right Eye (OD)'), ('OS', 'Left Eye (OS)')], max_length=2)),
                ('fundus_image', models.ImageField(blank=True, null=True, upload_to='fundus/')),
                ('ai_diagnosis', models.CharField(choices=[('0', 'No DR (Stage 0)'), ('1', 'Mild NPDR (Stage 1)'), ('2', 'Moderate NPDR (Stage 2)'), ('3', 'Severe NPDR (Stage 3)'), ('4', 'Proliferative DR (Stage 4)')], default='0', max_length=1)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('clinical_findings', models.JSONField(default=dict)),
                ('referral_urgency', models.CharField(choices=[('routine', 'Routine (12 Months)'), ('priority', 'Priority (3–4 Weeks)'), ('urgent', 'Urgent (< 7 Days)')], default='routine', max_length=10)),
                ('referral_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='screening.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_number', models.CharField(max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('printed', models.BooleanField(default=False)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screening.screening')),
            ],
        ),
    ]
