# Generated by Django 6.0.3 on 2026-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_phcworker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='dr_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='screening',
            name='gradcam_image',
            field=models.ImageField(blank=True, null=True, upload_to='gradcam/'),
        ),
        migrations.AddField(
            model_name='screening',
            name='low_confidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='screening',
            name='quality_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='screening',
            name='quality_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='screening',
            name='quality_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screening',
            name='referable',
            field=models.BooleanField(default=False),
        ),
    ]
