# Generated by Django 6.0.3 on 2026-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_screening_dr_level_screening_gradcam_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diabetes_duration',
            field=models.DecimalField(decimal_places=1, help_text='Years', max_digits=4),
        ),
    ]
