# Generated by Django 5.0.6 on 2026-09-07 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_employees(apps, schema_editor):
    Employee = apps.get_model('screening', 'Employee')
    PHCWorker = apps.get_model('screening', 'PHCWorker')
    for worker in PHCWorker.objects.select_related('user').all():
        full_name = f'{worker.user.first_name} {worker.user.last_name}'.strip() or worker.user.username
        Employee.objects.get_or_create(
            employee_id=worker.phc_id,
            defaults={
                'full_name': full_name,
                'role': 'PHC Worker',
                'department': worker.unit or worker.phc_name,
                'phone': worker.phone_number or '',
                'email': worker.user.email or '',
                'is_active': worker.user.is_active,
                'user_id': worker.user_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_alter_patient_diabetes_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='PHC Worker', max_length=80)),
                ('department', models.CharField(default='PHC', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_employees, migrations.RunPython.noop),
    ]
