import { Eye, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Badge, { severityTone } from '../components/Badge';
import { Empty, ErrorState, Loading } from '../components/State';
import { api } from '../services/api';

export default function History() { const [patients, setPatients] = useState([]); const [rows, setRows] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { api.patients().then(async (list) => { setPatients(list); const results = await Promise.all(list.map(async (patient) => { try { return { patient, screening: await api.screening(patient.patient_id) }; } catch { return null; } })); setRows(results.filter(Boolean)); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []); const filtered = useMemo(() => rows.filter(({ patient, screening }) => `${patient.first_name} ${patient.last_name} ${patient.patient_id} ${screening.predicted_class}`.toLowerCase().includes(query.toLowerCase())), [rows, query]); return <><PageHeader eyebrow="Records" title="Screening history" description="Review the latest screening returned for every patient in the registry."/><div className="toolbar"><div className="search-field"><Search size={17}/><input placeholder="Search patient or result" value={query} onChange={(e) => setQuery(e.target.value)}/></div></div>{error ? <ErrorState message={error}/> : loading ? <Loading/> : filtered.length === 0 ? <Empty title="No screening history" message="Completed screenings will appear here."/> : <div className="table-card"><div className="table-scroll"><table><thead><tr><th>Patient</th><th>Date</th><th>Prediction</th><th>Confidence</th><th>Referral</th><th/></tr></thead><tbody>{filtered.map(({ patient, screening }) => <tr key={patient.patient_id}><td><b>{patient.first_name} {patient.last_name}</b><small>{patient.patient_id}</small></td><td>{screening.screening_date ? new Date(screening.screening_date).toLocaleDateString() : '—'}</td><td><Badge tone={severityTone(screening.dr_level)}>{screening.predicted_class}</Badge><small>Level {screening.dr_level}</small></td><td>{screening.confidence}%</td><td>{screening.referral_urgency || '—'}</td><td><Link className="icon-link" to={`/patients/${patient.patient_id}`} aria-label="View screening"><Eye size={17}/></Link></td></tr>)}</tbody></table></div></div>}</>; }
