import { ArrowLeft, FileText, ScanEye } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Badge, { severityTone } from '../components/Badge';
import GradCam from '../components/GradCam';
import { ErrorState, Loading, Empty } from '../components/State';
import { api, mediaUrl } from '../services/api';

export default function PatientDetails() { const { patientId } = useParams(); const navigate = useNavigate(); const [patient, setPatient] = useState(null); const [screening, setScreening] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { Promise.all([api.patients(), api.screening(patientId)]).then(([patients, result]) => { setPatient(patients.find((item) => item.patient_id === patientId)); setScreening(result); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [patientId]); if (loading) return <Loading/>; if (error && !screening) return <ErrorState message={error}/>; if (!patient) return <Empty title="Patient not found"/>; return <><PageHeader eyebrow="Patient detail" title={`${patient.first_name} ${patient.last_name}`} description={`${patient.patient_id} · ${patient.age} years · ${patient.gender}`} action={<button className="button ghost" onClick={() => navigate(-1)}><ArrowLeft size={16}/> Back</button>}/><div className="detail-grid"><div className="card patient-summary"><span className="avatar large">{patient.first_name?.[0]}{patient.last_name?.[0] || ''}</span><h3>Patient information</h3><dl><div><dt>Patient ID</dt><dd>{patient.patient_id}</dd></div><div><dt>Age</dt><dd>{patient.age}</dd></div><div><dt>Sex</dt><dd>{patient.gender}</dd></div></dl><Link className="button primary wide" to="/screening/new"><ScanEye size={17}/> New screening</Link></div>{screening ? <div className="detail-main"><div className="card result-card"><div className="card-top"><div><span className="eyebrow">Latest AI result</span><h3>{screening.predicted_class}</h3></div><Badge tone={severityTone(screening.dr_level)}>DR Level {screening.dr_level}</Badge></div><div className="result-details"><div><small>Confidence</small><b>{screening.confidence}%</b></div><div><small>Referral urgency</small><b>{screening.referral_urgency || '—'}</b></div><div><small>Quality</small><b>{screening.quality_passed ? 'Passed' : 'Review'}</b></div></div><div className="detail-actions"><Link className="button secondary" to={`/reports/${screening.screening_id}`}><FileText size={16}/> Screening report</Link></div></div><div className="visual-grid">{screening.image_url && <div className="image-panel"><div className="image-panel-head"><b>Fundus image</b></div><img src={mediaUrl(screening.image_url)} alt="Fundus image"/></div>}<GradCam url={screening.gradcam_url}/></div></div> : <Empty title="No screening found" message="This patient does not have a screening result yet."/>}</div></>; }
