import { ArrowLeft, Printer } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import Badge, { severityTone } from '../components/Badge';
import GradCam from '../components/GradCam';
import { ErrorState, Loading } from '../components/State';
import { api, mediaUrl } from '../services/api';

export default function Report() { const { screeningId } = useParams(); const navigate = useNavigate(); const [report, setReport] = useState(null); const [error, setError] = useState(''); useEffect(() => { api.referral(screeningId).then(setReport).catch((err) => setError(err.message)); }, [screeningId]); if (error) return <ErrorState message={error}/>; if (!report) return <Loading label="Loading screening report..."/>; return <><PageHeader eyebrow="Clinical report" title="Screening report" description={`Report ${report.slip_number || `#${screeningId}`} · ${report.screening_date ? new Date(report.screening_date).toLocaleString() : ''}`} action={<div className="button-row"><button className="button ghost" onClick={() => navigate(-1)}><ArrowLeft size={16}/> Back</button><button className="button secondary" onClick={() => window.print()}><Printer size={16}/> Print</button></div>}/><article className="report-sheet"><div className="report-header"><div><span className="eyebrow">DR VISION AI / PHC RAMPUR</span><h3>Diabetic retinopathy screening report</h3></div><Badge tone={severityTone(report.dr_level)}>DR Level {report.dr_level}</Badge></div><div className="report-patient"><div><small>Patient</small><b>{report.patient_name}</b></div><div><small>Patient ID</small><b>{report.patient_id}</b></div><div><small>Examined eye</small><b>{report.eye_side}</b></div><div><small>Referral urgency</small><b>{report.referral_urgency || '—'}</b></div></div><div className="report-result"><span className="eyebrow">Model output</span><h2>{report.predicted_class}</h2><div className="report-stat"><strong>{report.confidence}%</strong><span>confidence returned by the AI model</span></div><p>{report.referable ? 'This result is marked referable by the backend and requires appropriate clinical review.' : 'This result is not marked referable by the backend.'}</p></div><div className="report-images">{report.image_url && <div className="image-panel"><div className="image-panel-head"><b>Fundus image</b></div><img src={mediaUrl(report.image_url)} alt="Fundus image in screening report"/></div>}<GradCam url={report.gradcam_url}/></div><div className="report-note"><b>Clinical note</b><span>AI output supports qualified clinical review and does not replace diagnosis.</span></div></article></>; }
